server:
  port: 8080

spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
  datasource:
    initialization-mode: always
    platform: dev
    url: jdbc:h2:mem:bankaccount
    username: sg
    password: password
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true

app:
  jwtSecret: Rw4Xv42sK(c9X;4X@;%t
  jwtExpirationMs: 86400000

logging:
  level:
    com.cberthier.bankaccount: DEBUG