INSERT INTO ROLES (ID, NAME) VALUES (1, 'ROLE_ADMIN');
INSERT INTO ROLES (ID, NAME) VALUES (2, 'ROLE_CLIENT');
INSERT INTO CLIENT (ID, EMAIL, PASSWORD, FIRST_NAME, LAST_NAME) VALUES (10, 'cberthier@oxiane.com', '$2a$10$rZHn6UFjrQWHWFi6sBmrJeykmybnRzW3t7p5ZHDyxHUG3UKxZ2nNC', 'Cyril', 'BERTHIER');
INSERT INTO ACCOUNT (ID, NAME, CLIENT_ID, BALANCE) VALUES (100, 'MyAccount', 10, 100);
INSERT INTO CLIENT_ROLES (CLIENT_ID, ROLE_ID) VALUES (10, 2);